import { useSelector } from "react-redux";

const CompleteFinancialData = () => {
  const userInfo = useSelector((state) => state.user);
  //   const transactionData = useSelector((state) => state.transactions);

  const seedrandom = require("seedrandom");

  // Set a seed value (you can change this to any string you like)
  const seed = "mySeed123";

  // Use seedrandom to create a seeded random number generator
  const rng = seedrandom(seed);

  // Function to get a consistent random amount
  const getRandomAmount = () => (rng() * 1000).toFixed(2);
  const reference = () => (rng() * 1000000000000).toFixed(0);

  // const DecemberTransaction = [
  //   {
  //     Account: 111333,b
  //     Name: "William Brown",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-01",
  //     Description: "Utility Bill Payment",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 444555,
  //     Name: "Emma Taylor",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-02",
  //     Description: "Stock Purchase",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 666777,
  //     Name: "James Wilson",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-03",
  //     Description: "Marketing Expenses",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 888999,
  //     Name: "Ava Johnson",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-04",
  //     Description: "Client Payment",
  //     Debit: 0.0,
  //     Credit: parseFloat(getRandomAmount()),
  //   },
  //   {
  //     Account: 222333,
  //     Name: "Noah Davis",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-05",
  //     Description: "Training Fee",
  //     Debit: 0.0,
  //     Credit: parseFloat(getRandomAmount()),
  //   },
  //   {
  //     Account: 555444,
  //     Name: "Sophie Taylor",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-06",
  //     Description: "Software Subscription",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 777666,
  //     Name: "Ethan Miller",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-07",
  //     Description: "Website Development",
  //     Debit: 0.0,
  //     Credit: parseFloat(getRandomAmount()),
  //   },
  //   {
  //     Account: 999888,
  //     Name: "Isabella Anderson",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-08",
  //     Description: "Insurance Premium",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 333222,
  //     Name: "Liam Brown",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-09",
  //     Description: "Conference Registration",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 666999,
  //     Name: "Sophie Taylor",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-10",
  //     Description: "Software Subscription",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 888111,
  //     Name: "Jackson Wilson",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-11",
  //     Description: "Repair Expenses",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  //   {
  //     Account: 222444,
  //     Name: "Chloe Johnson",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-12",
  //     Description: "Royalty Income",
  //     Debit: 0.0,
  //     Credit: parseFloat(getRandomAmount()),
  //   },
  //   {
  //     Account: 111222,
  //     Name: "Emily Davis",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-13",
  //     Description: "Consulting Fee",
  //     Debit: 0.0,
  //     Credit: parseFloat(getRandomAmount()),
  //   },
  //   {
  //     Account: 333444,
  //     Name: "Daniel Johnson",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-14",
  //     Description: "Product Sale",
  //     Debit: 0.0,
  //     Credit: parseFloat(getRandomAmount()),
  //   },
  //   {
  //     Account: 555666,
  //     Name: "Olivia White",
  //     ReferenceNo: parseFloat(reference()),
  //     Date: "2024-04-15",
  //     Description: "Expense Reimbursement",
  //     Debit: parseFloat(getRandomAmount()),
  //     Credit: 0.0,
  //   },
  // ];

  const NovemberTransaction = [
    // {
    //   Account: 8474930,
    //   Name: "Jame Willson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-30",
    //   Description: "Housing Investing",
    //   Debit: 0.0,
    //   Credit: "860,800",
    // },
    // {
    //   Account: 987654,
    //   Name: "Martins Richman",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-30",
    //   Description: "Consultation Fee",
    //   Debit: 0.0,
    //   Credit: userInfo.amount,
    // },
    // {
    //   Account: 123456,
    //   Name: "John Trevor",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-30",
    //   Description: "Payment for Services",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 789012,
    //   Name: "Jane Smith",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-29",
    //   Description: "Product Purchase",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 456789,
    //   Name: "Bob Johnson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-29",
    //   Description: "Rent Payment",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 654321,
    //   Name: "Eva Wilson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-28",
    //   Description: "Office Supplies",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 123789,
    //   Name: "David Lee",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-27",
    //   Description: "Salary Deposit",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 456123,
    //   Name: "Sara Davis",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-26",
    //   Description: "Advertising Expense",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 789456,
    //   Name: "Michael Johnson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-26",
    //   Description: "Loan Repayment",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 321654,
    //   Name: "Laura White",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-23",
    //   Description: "Travel Expenses",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 654987,
    //   Name: "Chris Taylor",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-20",
    //   Description: "Dividend Income",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 111222,
    //   Name: "Emily Davis",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-20",
    //   Description: "Consulting Fee",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 333444,
    //   Name: "Daniel Johnson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-18",
    //   Description: "Product Sale",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 555666,
    //   Name: "Olivia White",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-16",
    //   Description: "Expense Reimbursement",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 777888,
    //   Name: "Matthew Miller",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-17",
    //   Description: "Equipment Purchase",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 999000,
    //   Name: "Sophia Anderson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-17",
    //   Description: "Freelance Income",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // Additional transactions...
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-11-1",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // {
    //   Account: 444555,
    //   Name: "Emma Taylor",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-20",
    //   Description: "Stock Purchase",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 666777,
    //   Name: "James Wilson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-21",
    //   Description: "Marketing Expenses",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-11-03",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    // {
    //   Account: 222333,
    //   Name: "Noah Davis",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-23",
    //   Description: "Training Fee",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 555444,
    //   Name: "Grace White",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-24",
    //   Description: "Rent Expense",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 777666,
    //   Name: "Ethan Miller",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-25",
    //   Description: "Website Development",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // {
    //   Account: 999888,
    //   Name: "Isabella Anderson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-26",
    //   Description: "Insurance Premium",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 333222,
    //   Name: "Liam Brown",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-27",
    //   Description: "Conference Registration",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 666999,
    //   Name: "Sophie Taylor",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-28",
    //   Description: "Software Subscription",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 888111,
    //   Name: "Jackson Wilson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-29",
    //   Description: "Repair Expenses",
    //   Debit: parseFloat(getRandomAmount()),
    //   Credit: 0.0,
    // },
    // {
    //   Account: 222444,
    //   Name: "Chloe Johnson",
    //   ReferenceNo: parseFloat(reference()),
    //   Date: "2024-11-30",
    //   Description: "Royalty Income",
    //   Debit: 0.0,
    //   Credit: parseFloat(getRandomAmount()),
    // },
    // Add more objects for additional transactions
  ];

  const OctoberTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-1",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-2",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-3",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-4",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-5",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Grace White",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-6",
      Description: "Rent Expense",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-7",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-8",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-9",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888111,
      Name: "Jackson Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-11",
      Description: "Repair Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 222444,
      Name: "Chloe Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-10-12",
      Description: "Royalty Income",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    // Add more objects for additional transactions
  ];

  const SeptemberTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888111,
      Name: "Jackson Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-11",
      Description: "Repair Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 222444,
      Name: "Chloe Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-12",
      Description: "Royalty Income",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 111222,
      Name: "Emily Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-13",
      Description: "Consulting Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 333444,
      Name: "Daniel Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-14",
      Description: "Product Sale",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555666,
      Name: "Olivia White",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-15",
      Description: "Expense Reimbursement",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777888,
      Name: "Matthew Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-16",
      Description: "Equipment Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 999000,
      Name: "Sophia Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-17",
      Description: "Freelance Income",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-17",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-17",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-09-17",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in September
  ];

  const AugustTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888111,
      Name: "Jackson Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-11",
      Description: "Repair Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 222444,
      Name: "Chloe Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-12",
      Description: "Royalty Income",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 111222,
      Name: "Emily Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-13",
      Description: "Consulting Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 333444,
      Name: "Daniel Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-14",
      Description: "Product Sale",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555666,
      Name: "Olivia White",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-08-15",
      Description: "Expense Reimbursement",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in August
  ];

  const JulyTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-07-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in July
  ];

  const JuneTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-06-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in June
  ];

  const MayTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888111,
      Name: "Jackson Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-11",
      Description: "Repair Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 222444,
      Name: "Chloe Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-12",
      Description: "Royalty Income",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 111222,
      Name: "Emily Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-13",
      Description: "Consulting Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 333444,
      Name: "Daniel Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-14",
      Description: "Product Sale",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555666,
      Name: "Olivia White",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-05-15",
      Description: "Expense Reimbursement",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in May
  ];

  const AprilTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888111,
      Name: "Jackson Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-11",
      Description: "Repair Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 222444,
      Name: "Chloe Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-12",
      Description: "Royalty Income",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 111222,
      Name: "Emily Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-13",
      Description: "Consulting Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 333444,
      Name: "Daniel Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-14",
      Description: "Product Sale",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555666,
      Name: "Olivia White",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-04-15",
      Description: "Expense Reimbursement",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in April
  ];

  const MarchTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-03-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in March
  ];

  const FebruaryTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-02-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in February
  ];

  const JanuaryTransaction = [
    {
      Account: 111333,
      Name: "William Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-01",
      Description: "Utility Bill Payment",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 444555,
      Name: "Emma Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-02",
      Description: "Stock Purchase",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666777,
      Name: "James Wilson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-03",
      Description: "Marketing Expenses",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 888999,
      Name: "Ava Johnson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-04",
      Description: "Client Payment",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 222333,
      Name: "Noah Davis",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-05",
      Description: "Training Fee",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 555444,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-06",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 777666,
      Name: "Ethan Miller",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-07",
      Description: "Website Development",
      Debit: 0.0,
      Credit: parseFloat(getRandomAmount()),
    },
    {
      Account: 999888,
      Name: "Isabella Anderson",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-08",
      Description: "Insurance Premium",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 333222,
      Name: "Liam Brown",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-09",
      Description: "Conference Registration",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    {
      Account: 666999,
      Name: "Sophie Taylor",
      ReferenceNo: parseFloat(reference()),
      Date: "2024-01-10",
      Description: "Software Subscription",
      Debit: parseFloat(getRandomAmount()),
      Credit: 0.0,
    },
    // Add more objects for additional transactions in January
  ];

  const completeFinancialData = [
    ...JanuaryTransaction,
    ...FebruaryTransaction,
    ...MarchTransaction,
    ...AprilTransaction,
    ...MayTransaction,
    ...JuneTransaction,
    ...JulyTransaction,
    ...AugustTransaction,
    ...SeptemberTransaction,
    ...OctoberTransaction,
    ...NovemberTransaction,
    // ...DecemberTransaction,
  ];

  return completeFinancialData;
};

export default CompleteFinancialData;
